name: Autotrader Client Runner
run-name: ${{ github.actor }} is running AT client
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - run: run ./client
