name: Autotrader Client Runner
run-name: ${{ github.actor }} is running AT client
on: workflow_dispatch
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: build/client
