name: Autotrader Client Runner
run-name: ${{ github.actor }} is running AT client
on: workflow_dispatch
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ls ${{ github.workspace }}
      - run: ${{ github.workspace }}/client
